<?php
//  ------------------------------------------------------------------------ //
//                      SOCIALNET - MODULE FOR XOOPS 2                       //
//                  Copyright (c) 2009-2010  David Yanez Osses               //
//                     <http://www.ipwgc.com/>                      		 //
// ------------------------------------------------------------------------- //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

include_once 'admin_header.php';
require_once '../../../include/cp_header.php';
require_once XOOPS_ROOT_PATH.'/modules/socialnet/include/common.php';
require_once XOOPS_ROOT_PATH.'/modules/socialnet/admin/functions.php';
require_once XOOPS_ROOT_PATH.'/class/pagenav.php';
xoops_cp_header();
adminmenu(31);

// *******************************************************************************
// **** Main
// *******************************************************************************

echo"<html>"
  . "<head>"
  . "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">"
  . "<meta name=\"GENERATOR\" content=\"Microsoft FrontPage 4.0\">"
  . "<meta name=\"ProgId\" content=\"FrontPage.Editor.Document\">"
  . "<title></title>"
  . ""
  . "</head>"
  . ""
  . "<body>"
  . "<p><br>"
  . "</p>"
  . "<table border=\"1\" width=\"100%\" cellspacing=\"0\" bordercolor=\"#0066CC\" cellpadding=\"2\">"
  . "  <tr>"
  . "    <td width=\"24%\" bgcolor=\"#FFFFCC\">"
  . "      <p align=\"left\"><img border=\"0\" src=\"http://www.ipwgc.com/images/news/hit.gif\" width=\"125\" height=\"70\"><font size=\"3\"><b><br>"
  . "      <br>"
  . "      <a href=\"http://www.ipwgc.com/socialnet/modules/socialnet/treemenu.php/?tac=2\">"
  . "      <img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/help.gif\" alt=\"Tutorial SocialNet 2010\" align=\"left\" width=\"48\" height=\"48\"></a></b></font><a href=\"http://www.ipwgc.com/socialnet/modules/socialnet/treemenu.php/?tac=2\"><br>"
  . "      TUTORIAL SOCIALNET 2010</a></td>"
  . "    <td width=\"76%\" bgcolor=\"#FFFFCC\">"
  . "      <p align=\"center\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/banner22.gif\" width=\"508\" height=\"161\"></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"100%\" bgcolor=\"#008080\" colspan=\"2\">"
  . "      <p align=\"center\"><b><font color=\"#D8E3B8\"><font size=\"4\">These are the invited modules"
  . "      to the"
  . "      SocialNet 2010 project.&nbsp;<br>"
  . "      </font>SocialNet is based on the list of modules they are below, they had to be translated"
  . "      to english, and joined to one modulate.<br>"
  . "      Example: it not possible to upgrade the original yogurt module, because"
  . "      the code is totally different, in other word, in SocialNet don't exist any"
  . "      word relate to the code and word yogurt, and the same thing happens with the other invited modules to the SocialNet 2010 project.&nbsp;<br>"
  . "      <font size=\"4\">"
  . "      All the codes of the modules listings below were changed to this:"
  . "      &quot;socialnet&quot;</font><br>"
  . "      Developers: David Yanez Osses<br>"
  . "      </font><font color=\"#FFFF00\">"
  . "      CREDIT- UPDATE - OCTOBER, 01 2009</font></b></p>"
  . "    </td>"
  . "  </tr>"
  . "</table>"
  . "<table border=\"0\" width=\"100%\" cellpadding=\"4\" cellspacing=\"3\">"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>1</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/slogo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>"
  . "      [version] = 3.3 RC2<br>"
  . "      [author] = Marcello Brandao<br>"
  . "      [dirname] = yogurt</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"https://sourceforge.net/projects/galeriayogurt/\" target=\"_blank\"><b>https://sourceforge.net/projects/galeriayogurt/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>2</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/mpublish.gif\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" align=\"left\" bgcolor=\"#FFFFCC\"><b>[version] = 1.1;<br>"
  . "      [author]  = Fernando Santos<br>"
  . "      [dirname] = mastop_publish</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://www.mastop.com.br\" target=\"_blank\"><b>http://www.mastop.com.br</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>3</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/mgo2_logo.gif\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 1<br>"
  . "      [author]  = Fernando Santos<br>"
  . "      [dirname] = mastop_go2</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.mastop.com.br\" target=\"_blank\"><b>http://www.mastop.com.br</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>4</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/ams_slogo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" align=\"left\" bgcolor=\"#FFFFCC\"><b>\"AMS\"<br>"
  . "      [version] = 2.51 Final<br>"
  . "      [author] = NovaSmart Technology<br>"
  . "      [dirname] = AMS</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://www.novasmarttechnology.com\" target=\"_blank\"><b>http://www.novasmarttechnology.com</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>5</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/logo_userpage.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 1.5<br>"
  . "      [author] = Instant Zero<br>"
  . "      [dirname] = userpage</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.xoops.org/modules/news/article.php?storyid=5109\" target=\"_blank\"><b>xoops.instant-zero.com</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>6</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/xoopopchat.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" align=\"left\" bgcolor=\"#FFFFCC\"><b>[version] = 0.14<br>"
  . "      [author] =&nbsp; Y.Sakai<br>"
  . "      [dirname] = xoopopchat</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://www.bluemooninc.biz/\"><b>http://www.bluemooninc.biz/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>7</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/wblocks_logo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] 		= 0.2<br>"
  . "      [author] 		= Daniel Wilden and Julio Napuri<br>"
  . "      [dirname]=wblocks</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.esxoops.com\" target=\"_blank\"><b>http://www.esxoops.com</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>8</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/contact_slogo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" align=\"left\" bgcolor=\"#FFFFCC\"><b>[version] = 1.01<br>"
  . "      [author'] = \"\";<br>"
  . "      [dirname'] = contact</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://sourceforge.net/projects/xoops/files/\" target=\"_blank\"><b>http://sourceforge.net/projects/xoops/files/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>9</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/logo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 0.1<br>"
  . "      [author] = Onasre aka<br>"
  . "      [credits] = arabxoops.com<br>"
  . "      [dirname] = tools</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.arabxoops.com\" target=\"_blank\"><b>http://www.arabxoops.com</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>10</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/blockies.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" align=\"left\" bgcolor=\"#FFFFCC\"><b>[version] = 0.5<br>"
  . "      [author] = NS Tai (aka tuff)<br>"
  . "      [dirname] = blockies</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://www.brandycoke.com/\" target=\"_blank\"><b>http://www.brandycoke.com/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>11</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/clock_logo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 2<br>"
  . "      [author] =&nbsp; Orgin unknow<br>"
  . "      [dirname] = clock_calendar</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.pc-ressources.com\" target=\"_blank\"><b>http://www.pc-ressources.com</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>12</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/lang_tool_slogo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#FFFFCC\" align=\"left\"><b>[version] = 0.08<br>"
  . "      [author] =&nbsp; Finjon Kiang<br>"
  . "      [dirname] = lang_tool</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://dev.xoops.org/modules/xfmod/project/?lang_tool\" target=\"_blank\"><b>http://dev.xoops.org/modules/xfmod/project/?lang_tool</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>13</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/xoopsbb_slogo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 1.8<br>"
  . "      [author] =&nbsp; Kazumi Ono<br>"
  . "      [dirname] = newbbex</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.myweb.ne.jp/\" target=\"_blank\"><b>http://www.myweb.ne.jp/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\" align=\"center\"><b>14</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#FFFFCC\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/buddyfriends_logo.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#FFFFCC\" align=\"left\"><b>[version] = 2.4<br>"
  . "      [author] =&nbsp; Tim Cook<br>"
  . "      [dirname] = buddyfriends</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#FFFFCC\"><a href=\"http://www.xoops.org/modules/repository/singlefile.php?cid=97&amp;lid=1805\" target=\"_blank\"><b>http://www.xoops.org/modules/repository/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>15</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/birthday_slogo2.png\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 1.02<br>"
  . "      [author] =&nbsp; Sultan El Turrah<br>"
  . "      [dirname] = birthday</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><a href=\"http://www.xoops.org/modules/repository/singlefile.php?cid=113&amp;lid=1784\" target=\"_blank\"><b>http://www.xoops.org/modules/repository/</b></a></td>"
  . "  </tr>"
  . "  <tr>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\" align=\"center\"><b>16</b></td>"
  . "    <td width=\"11%\" bgcolor=\"#D8E3B8\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/MLS_Friends.gif\" width=\"92\" height=\"52\"></td>"
  . "    <td width=\"26%\" bgcolor=\"#D8E3B8\" align=\"left\"><b>[version] = 0.1<br>"
  . "      [author] =&nbsp; Marc Schot<br>"
  . "      [dirname] = MyLatinSoulmate Friends</b></td>"
  . "    <td width=\"63%\" bgcolor=\"#D8E3B8\"><b><a href=\"http://www.xoops.org/modules/repository/singlefile.php?cid=98&amp;lid=1648\" target=\"_blank\">http://www.xoops.org/modules/repository/</a></b></td>"
  . "  </tr>"
  . "</table>"
  . "<p align=\"center\"><img border=\"0\" src=\"http://www.ipwgc.com/socialnet/images/tutorial/credit/socialnetLogo.png\" width=\"92\" height=\"52\"><br>"
  . "<center><i>Maintain By <a href=\"http://www.ipwgc.com/socialnet/\">IPWGC.com"
  . "Project SocialNet 2010</a></i></center>"
  . "</p>"
  . ""
  . ""
  . "<p align=\"center\"><br>"
  . "</p>"
  . ""
  . "</body>"
  . ""
  . "</html>"
  . "
 .";

xoops_cp_footer();
?>

